Homework 1 is ready to rewiew
stoptime13/AnastasiiaKorenova pull request #1
Opened 2022-04-23 17:27 UTC by stoptime13

2022-04-24 13:41 UTC, obitkin requested changes
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestDiv.testAddition:24 expected [-1.84] but found [-1.8399999999999999]
[ERROR]   TestMult.testAddition:25 expected [-232.56] but found [-233.0]
[ERROR]   TestMult.testAddition:25 expected [-1806.88] but found [-1807.0]
[ERROR]   TestMult.testAddition:25 expected [271.61696968672] but found [271.0]
[ERROR]   TestSub.testAddition:24 expected [0.02] but found [0.020000000000003126]
```

Добавьте некоторую дельту в ваши ассерты. Думаю `-1.84 == -1.8399999999999999`

2022-04-24 13:41 UTC, obitkin commented on src/test/java/hw1/TestDiv.java
> +        double div = calculator.div(a, b);
Все тесты у вас называются `testAddition`

2022-05-05 14:09 UTC, stoptime13 commented on src/test/java/hw1/TestDiv.java
> +        double div = calculator.div(a, b);
Исправила названия тестов, а также ввела дельту.

2022-05-09 11:56 UTC, obitkin requested changes
Вы ввели дельту, но слишком большую, подогнанную под баги(а ни в коем случае нельзя подгонять тесты под баги) и теперь очевидные баги проходят тесты:

- 271.61 != 271.00
- -1806.88 != -1807.00

Надо найти такое значение, которое и очевидные баги не спрячет, но уберет неточности при вычислениях

`1e-4` для всех тестов подойдет

2022-09-25 13:10 UTC, obitkin approved these changes
Первая работа принята

2022-09-25 13:20 UTC, merged