Homework 2 is ready to rewiew
stoptime13/AnastasiiaKorenova pull request #2
Opened 2022-04-23 17:27 UTC by stoptime13

2022-04-24 15:23 UTC, obitkin requested changes

2022-04-24 15:23 UTC, obitkin commented on src/test/java/hw2/BeforeAfterTest.java
> +    }
Вообще софт ассерты не должны быть частью тестового класса. Уж точно не базового. У вас же не все тесты используют софт ассерты. Но при этом все наследуются от этого класса. Лучше создавать софт ассерт в тесте перед тем как вам нужно выполнить несколько проверок и потом вызывать `assertAll`

2022-04-24 15:23 UTC, obitkin commented on src/test/java/hw2/ex2/TestEx2.java
> +        }
Нужны фигурные скобки для if, так легко сломать условие

2022-04-24 15:23 UTC, obitkin commented on src/test/java/hw2/ex1/TestEx1.java
> +    }
А где вызов `softAssert.assertAll`? У вас так проверок нету

2022-04-24 15:23 UTC, obitkin commented on src/test/java/hw2/ex2/TestEx2.java
> +    }
Нету вызова `softAssert.assertAll`

2022-04-24 15:23 UTC, obitkin commented on src/test/java/hw2/BeforeAfterTest.java
> +        System.setProperty("webdriver.chrome.driver", path);
Вы перед каждым тестом задаете путь до драйвера. Вынесите в BeforeSuit

2022-05-05 14:52 UTC, stoptime13 commented on src/test/java/hw2/ex2/TestEx2.java
> +        }
Поправила.

2022-05-05 14:52 UTC, stoptime13 commented on src/test/java/hw2/BeforeAfterTest.java
> +    }
Поправила. Убрала softAssert из базового класса.

2022-05-05 14:53 UTC, stoptime13 commented on src/test/java/hw2/ex1/TestEx1.java
> +    }
Добавила вызов `softAssert.assertAll`.

2022-05-05 14:53 UTC, stoptime13 commented on src/test/java/hw2/ex2/TestEx2.java
> +    }
Поправила.

2022-05-09 12:01 UTC, obitkin approved these changes
Вторая работа принята

2022-09-25 13:20 UTC, merged